[package]
name = "webcrawler"
version = "0.3.4"
edition = "2021"
rust-version = "1.71.0"  # MSRV
description = "A library for crawling the web."
homepage = "https://spraakbanken.gu.se"
repository = "https://github.com/spraakbanken/webcrawler-rs"
license = "MIT"
include = ["*.md", "Cargo.toml", "LICENSE", "example/**/*", "src/**/*.rs"]

[workspace]
members = ["examples"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false

[dependencies]
async-trait = "0.1.82"
chrono = { version = "0.4.37", features = ["serde"] }
fs-err = { version = "3.2.1", features = ["expose_original_error"] }
futures = "0.3.30"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.43.1", features = ["macros", "rt", "signal", "sync"] }
tokio-stream = "0.1.16"
tokio-util = { version = "0.7.11", features = ["rt"] }
tracing = "0.1.41"
tracing_log_error = "0.1.4"
